version: '3.4'
services:
  app:
    image: gambero
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - RAILS_ENV # One of "development", "test", "production"
      - SECRET_KEY_BASE
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SENTRY_DSN
    # tmpfs's must be explicitly declared, because / is by default read-only (read_only: true).
    tmpfs:
      - /tmp
      - /gambero/tmp
      - /gambero/public/assets
    volumes:
      - ..:/gambero
      - ${GAMBERO_PATH:-/data}/log:/gambero/log
      - ${GAMBERO_PATH:-/data}/sphinx:/sphinx
    security_opt:
      - no-new-privileges
    read_only: true
    networks:
      default:
        ipv4_address: 172.20.0.2
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s

  db:
    image: mariadb
    volumes:
      - ${GAMBERO_PATH:-/data}/mariadb:/var/lib/mysql
    tmpfs:
      - /tmp
      - /run/mysqld
      - /var/run
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - SENTRY_DSN
    security_opt:
      - no-new-privileges
    networks:
      default:
        ipv4_address: 172.20.0.3
    read_only: true
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u $MYSQL_USER -p$MYSQL_PASSWORD -h 172.20.0.3 || exit 1"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 30s

  tarsnap:
    image: tarsnap
    depends_on:
      - db
    tmpfs:
      - /tmp
    volumes:
      - type: bind
        source: ${GAMBERO_PATH:-/data}/tarsnap.key
        target: /root/tarsnap.key
        read_only: true
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - SENTRY_DSN
    security_opt:
      - no-new-privileges
    networks:
      default:
        ipv4_address: 172.20.0.4

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24
